CREATE TABLE CUSTOMER(
CUST_ID VARCHAR(20) PRIMARY KEY UNIQUE, CUST_PASS VARCHAR(50) NOT NULL, CUST_NAME VARCHAR(30), gender ENUM('MALE','FEMALE'),CUST_PHONE long, CUST_ADDRESS VARCHAR(30),
CUST_CITY VARCHAR(60)  NOT NULL, WALLET_AMOUNT INT);

CREATE TABLE FOOD_VENDOR(
VEN_ID VARCHAR(20) PRIMARY KEY NOT NULL UNIQUE, VEN_PASS VARCHAR(50) NOT NULL,
VEN_NAME VARCHAR(40), VEN_PHONE long, VEN_ADDRESS VARCHAR(80), 
VEN_TYPE enum('NORTH INDIAN','SOUTH INDIAN','CHINESE','VEG','NON VEG'), VEN_CITY VARCHAR(50));

CREATE TABLE MENU(
FOOD_ID INT PRIMARY KEY auto_increment, FOOD_NAME varchar(100), FOOD_PRICE numeric,
FOOD_QUANTITY numeric, VEN_ID VARCHAR(50), 
CONSTRAINT menu_ven_fkid FOREIGN KEY(VEN_ID) REFERENCES FOOD_VENDOR(VEN_ID), 
FOOD_CAL numeric, FOOD_RATING varchar(5) DEFAULT '***', 
FOOD_TYPE enum('NorthIndian','SouthIndian','CHINESE','VEG','NonVeg','BEVERAGES','DESSERTS'));
